ProgrammersBlog.Mvc/Areas/Admin/Controllers/OptionsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Options;
using NToastNotify;
using ProgrammersBlog.Entities.Concrete;
using ProgrammersBlog.Mvc.Areas.Admin.Models;
using ProgrammersBlog.Services.Abstract;
using ProgrammersBlog.Shared.Utilities.Helpers.Abstract;

namespace ProgrammersBlog.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class OptionsController : Controller
    {
        private readonly AboutUsPageInfo _aboutUsPageInfo;
        private readonly IWritableOptions<AboutUsPageInfo> _aboutUsPageInfoWriter;
        private readonly IToastNotification _toastNotification;
        private readonly WebsiteInfo _websiteInfo;
        private readonly IWritableOptions<WebsiteInfo> _websiteInfoWriter;
        private readonly SmtpSettings _smtpSettings;
        private readonly IWritableOptions<SmtpSettings> _smtpSettingsWriter;
        private readonly ArticleRightSideBarWidgetOptions _articleRightSideBarWidgetOptions;
        private readonly IWritableOptions<ArticleRightSideBarWidgetOptions> _articleRightSideBarWidgetOptionsWriter;
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;

        public OptionsController(IOptionsSnapshot<AboutUsPageInfo> aboutUsPageInfo, IWritableOptions<AboutUsPageInfo> aboutUsPageInfoWriter, IToastNotification toastNotification, IOptionsSnapshot<WebsiteInfo> websiteInfo, IWritableOptions<WebsiteInfo> websiteInfoWriter, IOptionsSnapshot<SmtpSettings> smtpSettings, IWritableOptions<SmtpSettings> smtpSettingsWriter, IOptionsSnapshot<ArticleRightSideBarWidgetOptions> articleRightSideBarWidgetOptions, IWritableOptions<ArticleRightSideBarWidgetOptions> articleRightSideBarWidgetOptionsWriter, ICategoryService categoryService, IMapper mapper)
        {
            _aboutUsPageInfoWriter = aboutUsPageInfoWriter;
            _toastNotification = toastNotification;
            _websiteInfoWriter = websiteInfoWriter;
            _smtpSettingsWriter = smtpSettingsWriter;
            _articleRightSideBarWidgetOptionsWriter = articleRightSideBarWidgetOptionsWriter;
            _categoryService = categoryService;
            _mapper = mapper;
            _articleRightSideBarWidgetOptions = articleRightSideBarWidgetOptions.Value;
            _smtpSettings = smtpSettings.Value;
            _websiteInfo = websiteInfo.Value;
            _aboutUsPageInfo = aboutUsPageInfo.Value;
        }

        [HttpGet]
        public IActionResult About()
        {
            return View(_aboutUsPageInfo);
        }
        [HttpPost]
        public IActionResult About(AboutUsPageInfo aboutUsPageInfo)
        {
            if (ModelState.IsValid)
            {
                _aboutUsPageInfoWriter.Update(x =>
                {
                    x.Header = aboutUsPageInfo.Header;
                    x.Content = aboutUsPageInfo.Content;
                    x.SeoAuthor = aboutUsPageInfo.SeoAuthor;
                    x.SeoDescription = aboutUsPageInfo.SeoDescription;
                    x.SeoTags = aboutUsPageInfo.SeoTags;
                });
                _toastNotification.AddSuccessToastMessage("Hakkımızda Sayfa İçerikleri başarıyla güncellenmiştir.",new ToastrOptions
                {
                    Title = "Başarılı İşlem!"
                });
                return View(aboutUsPageInfo);

            }
            return View(aboutUsPageInfo);
        }
        [HttpGet]
        public IActionResult GeneralSettings()
        {
            return View(_websiteInfo);
        }
        [HttpPost]
        public IActionResult GeneralSettings(WebsiteInfo websiteInfo)
        {
            if (ModelState.IsValid)
            {
                _websiteInfoWriter.Update(x =>
                {
                    x.Title = websiteInfo.Title;
                    x.MenuTitle = websiteInfo.MenuTitle;
                    x.SeoAuthor = websiteInfo.SeoAuthor;
                    x.SeoDescription = websiteInfo.SeoDescription;
                    x.SeoTags = websiteInfo.SeoTags;
                });
                _toastNotification.AddSuccessToastMessage("Sitenizin genel ayarları başarıyla güncellenmiştir.", new ToastrOptions
                {
                    Title = "Başarılı İşlem!"
                });
                return View(websiteInfo);

            }
            return View(websiteInfo);
        }
        [HttpGet]
        public IActionResult EmailSettings()
        {
            return View(_smtpSettings);
        }
        [HttpPost]
        public IActionResult EmailSettings(SmtpSettings smtpSettings)
        {
            if (ModelState.IsValid)
            {
                _smtpSettingsWriter.Update(x =>
                {
                    x.Server = smtpSettings.Server;
                    x.Port = smtpSettings.Port;
                    x.SenderName = smtpSettings.SenderName;
                    x.SenderEmail = smtpSettings.SenderEmail;
                    x.Username = smtpSettings.Username;
                    x.Password = smtpSettings.Password;
                });
                _toastNotification.AddSuccessToastMessage("Sitenizin e-posta ayarları başarıyla güncellenmiştir.", new ToastrOptions
                {
                    Title = "Başarılı İşlem!"
                });
                return View(smtpSettings);

            }
            return View(smtpSettings);
        }
        [HttpGet]
        public async Task<IActionResult> ArticleRightSideBarWidgetSettings()
        {
            var categoriesResult = await _categoryService.GetAllByNonDeletedAndActiveAsync();
            var articleRightSideBarWidgetOptionsViewModel =
                _mapper.Map<ArticleRightSideBarWidgetOptionsViewModel>(_articleRightSideBarWidgetOptions);
            articleRightSideBarWidgetOptionsViewModel.Categories = categoriesResult.Data.Categories;
            return View(articleRightSideBarWidgetOptionsViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> ArticleRightSideBarWidgetSettings(ArticleRightSideBarWidgetOptionsViewModel articleRightSideBarWidgetOptionsViewModel)
        {
            var categoriesResult = await _categoryService.GetAllByNonDeletedAndActiveAsync();
            articleRightSideBarWidgetOptionsViewModel.Categories = categoriesResult.Data.Categories;
            if (ModelState.IsValid)
            {
                _articleRightSideBarWidgetOptionsWriter.Update(x =>
                {
                    x.Header = articleRightSideBarWidgetOptionsViewModel.Header;
                    x.TakeSize = articleRightSideBarWidgetOptionsViewModel.TakeSize;
                    x.CategoryId = articleRightSideBarWidgetOptionsViewModel.CategoryId;
                    x.FilterBy = articleRightSideBarWidgetOptionsViewModel.FilterBy;
                    x.OrderBy = articleRightSideBarWidgetOptionsViewModel.OrderBy;
                    x.IsAscending = articleRightSideBarWidgetOptionsViewModel.IsAscending;
                    x.StartAt = articleRightSideBarWidgetOptionsViewModel.StartAt;
                    x.EndAt = articleRightSideBarWidgetOptionsViewModel.EndAt;
                    x.MaxViewCount = articleRightSideBarWidgetOptionsViewModel.MaxViewCount;
                    x.MinViewCount = articleRightSideBarWidgetOptionsViewModel.MinViewCount;
                    x.MaxCommentCount = articleRightSideBarWidgetOptionsViewModel.MaxCommentCount;
                    x.MinCommentCount = articleRightSideBarWidgetOptionsViewModel.MinCommentCount;
                });
                _toastNotification.AddSuccessToastMessage("Makale sayfalarınızın widget ayarları başarıyla güncellenmiştir.", new ToastrOptions
                {
                    Title = "Başarılı İşlem!"
                });
                return View(articleRightSideBarWidgetOptionsViewModel);

            }
            return View(articleRightSideBarWidgetOptionsViewModel);
        }
    }
}

ProgrammersBlog.Mvc/Areas/Admin/Views/Options/About.cshtml
@model ProgrammersBlog.Entities.Concrete.AboutUsPageInfo

@{
    Layout = "_Layout";
    ViewBag.Title = "Hakkımızda Sayfa İçerikleri";

}
<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <div class="card mt-1 mb-1">
            <div class="card-header">
                <h4 class="text-center"><span class="fas fa-edit"></span> Hakkımızda Sayfa İçerikleri</h4>
            </div>
            <div class="card-body">
                <form asp-controller="Options" asp-action="About" method="post" id="form-aboutuspageinfo-update">
                    <div asp-validation-summary="All" class="text-danger" id="validation-summary"></div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label asp-for="Header"></label>
                            <input class="form-control" asp-for="Header" placeholder="Lütfen, başlık bilgisini giriniz." />
                            <span class="text-danger" asp-validation-for="Header"></span>
                        </div>
                        <div class="form-group col-md-12">
                            <label asp-for="Content"></label>
                            <textarea class="form-control" asp-for="Content" placeholder="Lütfen, içerik bilgisini giriniz." rows="4"></textarea>
                            <span class="text-danger" asp-validation-for="Content"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="SeoAuthor"></label>
                            <input type="text" class="form-control" asp-for="SeoAuthor" placeholder="Lütfen, seo yazar bilgisini giriniz." />
                            <span class="text-danger" asp-validation-for="SeoAuthor"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="SeoTags"></label>
                            <input type="text" class="form-control" asp-for="SeoTags" placeholder="Lütfen, seo etiket bilgisini giriniz." />
                            <span class="text-danger" asp-validation-for="SeoTags"></span>
                        </div>
                        <div class="form-group col-md-12">
                            <label asp-for="SeoDescription"></label>
                            <input type="text" class="form-control" asp-for="SeoDescription" placeholder="Lütfen, seo açıklama bilgisinizi giriniz." />
                            <span class="text-danger" asp-validation-for="SeoDescription"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <button type="submit" class="btn btn-primary"><span class="fas fa-save"></span> Kaydet</button>
                            <a class="btn btn-danger" asp-area="Admin" asp-controller="Home" asp-action="Index"><span class="fas fa-times"></span> İptal</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

ProgrammersBlog.Mvc/Areas/Admin/Views/Options/ArticleRightSideBarWidgetSettings.cshtml
@using ProgrammersBlog.Entities.ComplexTypes
@model ProgrammersBlog.Mvc.Areas.Admin.Models.ArticleRightSideBarWidgetOptionsViewModel

@{
    Layout = "_Layout";
    ViewBag.Title = "Makale Sayfaları için Widget Ayarları";

}
<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <div class="card mt-1 mb-1">
            <div class="card-header">
                <h4 class="text-center"><span class="fas fa-edit"></span> Makale Sayfaları için Widget Ayarları</h4>
            </div>
            <div class="card-body">
                <form asp-controller="Options" asp-action="ArticleRightSideBarWidgetSettings" method="post" id="form-articlerightsidebarwidgetsettings-update">
                    <div asp-validation-summary="All" class="text-danger" id="validation-summary"></div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label asp-for="Header"></label>
                            <input class="form-control" asp-for="Header" placeholder="Lütfen, tercih ettiğiniz widget başlığını giriniz." />
                            <span class="text-danger" asp-validation-for="Header"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="TakeSize"></label>
                            <input type="number" class="form-control" asp-for="TakeSize" />
                            <span class="text-danger" asp-validation-for="TakeSize"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="filterByList" asp-for="FilterBy"></label>
                            <select id="filterByList" class="form-control" asp-for="FilterBy" asp-items="Html.GetEnumSelectList<FilterBy>()">
                                <option></option>
                            </select>
                            <span asp-validation-for="FilterBy" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="categoryList" asp-for="CategoryId"></label>
                            <select id="categoryList" class="form-control" asp-for="CategoryId" asp-items="@(new SelectList(Model.Categories,"Id","Name"))">
                                <option></option>
                            </select>
                            <span asp-validation-for="CategoryId" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="orderByList" asp-for="OrderBy"></label>
                            <select id="orderByList" class="form-control" asp-for="OrderBy" asp-items="Html.GetEnumSelectList<OrderBy>()">
                                <option></option>
                            </select>
                            <span asp-validation-for="OrderBy" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="isAscendingList" asp-for="IsAscending"></label>
                            <select id="isAscendingList" class="form-control" asp-for="IsAscending">
                                <option></option>
                                <option value="true">Artan</option>
                                <option value="false">Azalan</option>

                            </select>
                            <span asp-validation-for="IsAscending" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="startAtDatePicker" asp-for="StartAt"></label>
                            <input type="text" id="startAtDatePicker" class="form-control" value="@Model.StartAt.ToShortDateString()" asp-for="StartAt" />
                            <span asp-validation-for="StartAt" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="endAtDatePicker" asp-for="EndAt"></label>
                            <input type="text" id="endAtDatePicker" class="form-control" value="@Model.EndAt.ToShortDateString()" asp-for="EndAt" />
                            <span asp-validation-for="EndAt" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="MinViewCount"></label>
                            <input type="number" class="form-control" asp-for="MinViewCount" />
                            <span class="text-danger" asp-validation-for="MinViewCount"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="MaxViewCount"></label>
                            <input type="number" class="form-control" asp-for="MaxViewCount" />
                            <span class="text-danger" asp-validation-for="MaxViewCount"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="MinCommentCount"></label>
                            <input type="number" class="form-control" asp-for="MinCommentCount" />
                            <span class="text-danger" asp-validation-for="MinCommentCount"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="MaxCommentCount"></label>
                            <input type="number" class="form-control" asp-for="MaxCommentCount" />
                            <span class="text-danger" asp-validation-for="MaxCommentCount"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <button type="submit" class="btn btn-primary"><span class="fas fa-save"></span> Kaydet</button>
                            <a class="btn btn-danger" asp-area="Admin" asp-controller="Home" asp-action="Index"><span class="fas fa-times"></span> İptal</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts
{
    <script src="https://cdn.jsdelivr.net/npm/select2@@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA==" crossorigin="anonymous"></script>
    <script src="~/AdminLTE/js/articleRightSideBarWidgetSettings.js" type="application/ecmascript"></script>
}
@section Styles
{
    <link href="https://cdn.jsdelivr.net/npm/select2@@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/cupertino/jquery-ui.min.css" integrity="sha512-ug/p2fTnYRx/TfVgL8ejTWolaq93X+48/FLS9fKf7AiazbxHkSEENdzWkOxbjJO/X1grUPt9ERfBt21iLh2dxg==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/cupertino/theme.min.css" integrity="sha512-adRIgePtMQgAVB+Mfkhl+Nyva/WllWlFzJyyhYCjznU3Di+Z4SsYi1Rqsep11PYLpUsW/SjE4NXUkIjabQJCOQ==" crossorigin="anonymous" />
    <link href="~/AdminLTE/css/select2-bootstrap4.min.css" rel="stylesheet" />

}

ProgrammersBlog.Mvc/Areas/Admin/Views/Options/EmailSettings.cshtml
@model ProgrammersBlog.Entities.Concrete.SmtpSettings

@{
    Layout = "_Layout";
    ViewBag.Title = "E-Posta Ayarları";

}
<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <div class="card mt-1 mb-1">
            <div class="card-header">
                <h4 class="text-center"><span class="fas fa-edit"></span> E-Posta Ayarları</h4>
            </div>
            <div class="card-body">
                <form asp-controller="Options" asp-action="EmailSettings" method="post" id="form-emailsettings-update">
                    <div asp-validation-summary="All" class="text-danger" id="validation-summary"></div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label asp-for="Server"></label>
                            <input class="form-control" asp-for="Server" placeholder="Lütfen, smtp sunucu bilginizi giriniz." />
                            <span class="text-danger" asp-validation-for="Server"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Port"></label>
                            <input type="number" class="form-control" asp-for="Port" placeholder="Lütfen, smtp port bilginizi giriniz." />
                            <span class="text-danger" asp-validation-for="Port"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="SenderName"></label>
                            <input type="text" class="form-control" asp-for="SenderName" placeholder="Lütfen, gönderen adı bilginizi giriniz." />
                            <span class="text-danger" asp-validation-for="SenderName"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="SenderEmail"></label>
                            <input type="text" class="form-control" asp-for="SenderEmail" placeholder="Lütfen, gönderen e-posta adresi bilginizi giriniz." />
                            <span class="text-danger" asp-validation-for="SenderEmail"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Username"></label>
                            <input type="text" class="form-control" asp-for="Username" placeholder="Lütfen, kullanıcı adı/e-posta bilginizi giriniz." />
                            <span class="text-danger" asp-validation-for="Username"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Password"></label>
                            <input type="password" class="form-control" asp-for="Password" placeholder="Lütfen, şifre bilginizi giriniz." />
                            <span class="text-danger" asp-validation-for="Password"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <button type="submit" class="btn btn-primary"><span class="fas fa-save"></span> Kaydet</button>
                            <a class="btn btn-danger" asp-area="Admin" asp-controller="Home" asp-action="Index"><span class="fas fa-times"></span> İptal</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

ProgrammersBlog.Mvc/Areas/Admin/Views/Options/GeneralSettings.cshtml
@model ProgrammersBlog.Entities.Concrete.WebsiteInfo

@{
    Layout = "_Layout";
    ViewBag.Title = "Genel Ayarlar";

}
<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <div class="card mt-1 mb-1">
            <div class="card-header">
                <h4 class="text-center"><span class="fas fa-edit"></span> Genel Ayarlar</h4>
            </div>
            <div class="card-body">
                <form asp-controller="Options" asp-action="GeneralSettings" method="post" id="form-generalsettings-update">
                    <div asp-validation-summary="All" class="text-danger" id="validation-summary"></div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label asp-for="Title"></label>
                            <input class="form-control" asp-for="Title" placeholder="Lütfen, sitenizin adını giriniz." />
                            <span class="text-danger" asp-validation-for="Title"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="MenuTitle"></label>
                            <input class="form-control" asp-for="MenuTitle" placeholder="Lütfen, menünüz için sitenizin adını giriniz." />
                            <span class="text-danger" asp-validation-for="MenuTitle"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="SeoAuthor"></label>
                            <input type="text" class="form-control" asp-for="SeoAuthor" placeholder="Lütfen, sitenizin seo yazar bilgisini giriniz." />
                            <span class="text-danger" asp-validation-for="SeoAuthor"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="SeoTags"></label>
                            <input type="text" class="form-control" asp-for="SeoTags" placeholder="Lütfen, sitenizin seo etiket bilgisini giriniz." />
                            <span class="text-danger" asp-validation-for="SeoTags"></span>
                        </div>
                        <div class="form-group col-md-12">
                            <label asp-for="SeoDescription"></label>
                            <input type="text" class="form-control" asp-for="SeoDescription" placeholder="Lütfen, sitenizin seo açıklama bilgisinizi giriniz." />
                            <span class="text-danger" asp-validation-for="SeoDescription"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <button type="submit" class="btn btn-primary"><span class="fas fa-save"></span> Kaydet</button>
                            <a class="btn btn-danger" asp-area="Admin" asp-controller="Home" asp-action="Index"><span class="fas fa-times"></span> İptal</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>